---
title: "Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Load Libraries
```{r}
library(haven)
library(dplyr)
```
 


## Load data
```{r}


allPatients = file.path("../","All_Data_Patientstudy.sav")
allDataPDGroups = file.path("../", "All_Data_PD_GroupPatientstudy.sav")

allDataPatientStudyDS = read_sav(allPatients)
allDataPDGroupsStudyDS = read_sav(allDataPDGroups)

```


## First glimpse
```{r}
glimpse(allDataPatientStudyDS)
glimpse(allDataPDGroupsStudyDS)
```
```{r}
variable.names(allDataPatientStudyDS)
```

```{r}
#Table 1
Table1_allDataPDGroups <- allDataPDGroupsStudyDS %>%
select("Age", "Medication", "Length_Parkinson","H_Y")

selectedVarallDataPDGroups
skimr::skim(selectedVarallDataPDGroups)
```
```{r}
Table1_AllDataPatient <- allDataPatientStudyDS %>%
  filter(Group == "1")%>%
select("Group","Age", "Medication", "Length_Parkinson","H_Y")


selectedVarallDataPDGroups
skimr::skim(selectedVarallDataPDGroups)
```



```{r}
#Table 2

Table2_AllDataPatient <- allDataPatientStudyDS %>%
  group_by(Group)%>%
select("Age", "Sex", "Handedness","MMSE","RAVEN")

Table2_AllDataPatient
skimr::skim(Table2_AllDataPatient)

Table2_AllDataPatient%>%
  group_by(Group)%>%
  count(Sex=="1")


  


```










