---
title: "Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Load Libraries
```{r}
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(moderndive)
```
 


## Load data
```{r}

allPatients = file.path("../","All_Data_Patientstudy.sav")
allDataPatientStudyDS = read_sav(allPatients)

tidied_dataset = read.csv("tidied-dataset.csv")

```

```{r}
glimpse(tidied_dataset)
```


## First glimpse
```{r}
glimpse(allDataPatientStudyDS)

```
```{r}
variable.names(allDataPatientStudyDS)
```
```{r}
allDataPatientStudyDS %>%
mutate(Sex = factor(Sex, labels = c("Female", "Male")),Group = factor(Group, labels = c("PD", "Control")))


```
```{r}
tidied_dataset <- tidied_dataset %>%
mutate(Sex = factor(Sex, labels = c("Male", "Female")),Group = factor(Group, labels = c("Control", "PD")))
```
```{r}
#Table 1 recreated using allDataPatientStudyDS dataframe
Table1 <- tidied_dataset %>%
  filter(Group == "PD")%>%
select("Group","Age", "Medication", "Length_Parkinson","H_Y")


Table1
skimr::skim(Table1)
```


```{r}
#Table 3 using tidied_dataset

Table3 <- tidied_dataset %>%
  select("Age", "Sex", "Handedness","MMSE","RAVEN","Group")%>%
  group_by(Group)%>%
  summarize(mean_age = mean(Age), mean_handedness = mean(Handedness),mean_MMSE = mean(MMSE), mean_Raven = mean(RAVEN), count = n())

Table3_count_gender <- tidied_dataset %>%
  select("Sex","Group")%>%
  group_by(Group,Sex)%>%
  summarize(count=n())

t(Table3)
Table3_count_gender


```


```{r}
#Table 4 using tidied dataset
Table4 <- tidied_dataset %>%
  group_by(Group)%>%
select("Phonologic_Fluency","Semantic_Fluency","BNT", "SyllSec_Norm", "SyllSec_Ruis", "NPro_Dur_Norm","NPro_Dur_Ruis")%>%
  summarise(mean_Phonologic_Fluency = mean(Phonologic_Fluency), sd_phonologic_fluency = sd(Phonologic_Fluency),
            mean_Semantic_Fluency = mean(Semantic_Fluency), sd_Semantic_Fluency = sd(Semantic_Fluency),
            mean_BNT = mean(BNT), sd_BNT = sd(BNT),
            mean_Syllsec_Norm = mean(SyllSec_Norm), sd_Syllsec_Norm = sd(SyllSec_Norm),
            mean_Syllsec_Ruis = mean(SyllSec_Ruis), sd_SyllSec_Ruis = sd(SyllSec_Ruis),
            mean_NPro_Dur_Norm = mean(NPro_Dur_Norm), sd_NPro_Dur_Norm = sd(NPro_Dur_Norm),
            mean_NPro_Dur_Ruis = mean(NPro_Dur_Ruis), sd_NPro_Dur_Ruis = sd(NPro_Dur_Ruis))
Table4
print(Table4, n = 15)
```


```{r}
#Table 9 using using tidied dataset
Table9_raw <- tidied_dataset %>%
  select("Group","Nrm_Reformulation","Nrm_FilledPause","Nrm_Repetition","Nois_Reformulation","Nois_FilledPause", "Nois_Repetition")

Table9 <- Table9_raw %>%
  gather (key = "Error_type", value = "Total_Number",-Group,"Nrm_Reformulation","Nrm_FilledPause","Nrm_Repetition","Nois_Reformulation","Nois_FilledPause", "Nois_Repetition")
Table9

aggregate(Total_Number~Error_type+Group,Table9,sum)
 

```
```{r}
Fig1_raw <- allDataPatientStudyDS %>%
  select("Group","Pct_NormRep","Pct_NoiseRep","PctSemNoiseRep","PctSemNormRep")%>%
  filter(Group == 0,complete.cases(Pct_NormRep,Pct_NoiseRep,PctSemNoiseRep,PctSemNormRep))%>%
  summarise(mean_Pct_NormRep=mean(Pct_NormRep),mean_Pct_NoiseRep=mean(Pct_NoiseRep),mean_PctSemNoiseRep=mean(PctSemNoiseRep),mean_PctSemNormRep=mean(PctSemNormRep, count=n()))
 
Fig1_table <- Fig1_raw %>%
  gather (key = "Error", value = "Percentage_Repaired","mean_PctSemNormRep","mean_PctSemNoiseRep","mean_Pct_NormRep","mean_Pct_NoiseRep")

ggplot(data = Fig1_table) +
  geom_col(mapping = aes(x = Error,y=Percentage_Repaired), binwidth = 0.5)
 
  
```
```{r}
Fig2_raw <- allDataPatientStudyDS %>%
  select("Group","Pct_NormRep","Pct_NoiseRep","PctSemNoiseRep","PctSemNormRep")%>%
  filter(complete.cases(Pct_NormRep,Pct_NoiseRep,PctSemNoiseRep,PctSemNormRep))%>%
  group_by(Group)%>%
  summarise(mean_Pct_NormRep=mean(Pct_NormRep),mean_Pct_NoiseRep=mean(Pct_NoiseRep),mean_PctSemNoiseRep=mean(PctSemNoiseRep),mean_PctSemNormRep=mean(PctSemNormRep, count=n()))
 
Fig2_table <- Fig2_raw %>%
  gather (key = "Error", value = "Percentage_Repaired","mean_PctSemNormRep","mean_PctSemNoiseRep","mean_Pct_NormRep","mean_Pct_NoiseRep")

Fig2_table %>%
  ggplot() +
  geom_col(mapping = aes(x = Error,y=Percentage_Repaired), binwidth = 0.5)+
  facet_wrap(~Group)
  
```

```{r}
Fig_table <- allDataPatientStudyDS %>%
  group_by(Group)%>%
  select("SemErrors_Norm","Nrm_Sem_Rep", "SemErrors_Noise","Nois_Sem_Rep", "Norm_ErrorsRepaired","Noise_ErrorsRepaired","TotalErrorsNorm_N","TotalErrorsNois_N" )%>%
  mutate(Nrm_Perc_Sem_Error_Repaired = Nrm_Sem_Rep/SemErrors_Norm * 100, Nois_Per_Sem_Error_Repaired = Nois_Sem_Rep/SemErrors_Noise *100, Nrm_Perc_Total_Error_Rep = Norm_ErrorsRepaired/TotalErrorsNorm_N *100, Nois_Per_Total_Error_Rep = Noise_ErrorsRepaired/TotalErrorsNois_N *100)%>%
replace(is.na(.), 0)%>%
group_by(Group) %>% 
summarize(Mean_Nrm_Perc_Sem_Error_Repaired = mean(Nrm_Perc_Sem_Error_Repaired),Mean_Nois_Per_Sem_Error_Repaired = mean(Nois_Per_Sem_Error_Repaired), Mean_Nrm_Perc_Total_Error_Repaired = mean(Nrm_Perc_Total_Error_Rep),Mean_Nois_Perc_Total_Error_Repaired = mean(Nois_Per_Total_Error_Rep))%>%
rename(Sem_Normal=Mean_Nrm_Perc_Sem_Error_Repaired, Sem_Noise=Mean_Nois_Per_Sem_Error_Repaired, Tot_Normal=Mean_Nrm_Perc_Total_Error_Repaired, Tot_Noise=Mean_Nois_Perc_Total_Error_Repaired)



Fig_table

skimr::skim(Fig_table)


```
```{r}
Fig1 <- Fig_table  %>%
  filter(Group==0)%>%
  gather (key = "Error", value = "Mean_Percentage_Repaired","Sem_Normal","Sem_Noise","Tot_Normal","Tot_Noise" )%>%
  ggplot() +
  geom_col(mapping = aes(x = Error,y=Mean_Percentage_Repaired), binwidth = 0.5)
 

Fig1
```


```{r}
Fig2 <- Fig_table  %>%
  gather (key = "Error", value = "Mean_Percentage_Repaired","Sem_Normal","Sem_Noise","Tot_Normal","Tot_Noise" )%>%
  ggplot() +
  geom_col(mapping = aes(x = Error,y=Mean_Percentage_Repaired), binwidth = 0.5)+
  facet_wrap(~Group)

Fig2
```
```{r}
Regression_table <- tidied_dataset %>%
  filter(Group == "PD",complete.cases(H_Y) )
```

```{r}
Model_sem_fluency <- lm(Semantic_Fluency~H_Y,Regression_table)

get_regression_table(Model_sem_fluency)
broom::glance(Model_sem_fluency)
```

```{r}
Model_BNT <- lm(BNT~H_Y,Regression_table)
get_regression_table(Model_BNT)
broom::glance(Model_BNT)
```
```{r}
Model_ProductionSpeedNormal <- lm(SyllSec_Norm~H_Y,Regression_table)
get_regression_table(Model_ProductionSpeedNormal)
broom::glance(Model_ProductionSpeedNormal)
```
```{r}
Model_ProductionSpeedNoise <- lm(SyllSec_Ruis~H_Y,Regression_table)
get_regression_table(Model_ProductionSpeedNoise)
broom::glance(Model_ProductionSpeedNoise)
```
```{r}
Model_DurationNorm <- 
lm(NPro_Dur_Norm~H_Y,Regression_table)
get_regression_table(Model_DurationNorm)
broom::glance(Model_DurationNorm)
```
```{r}
Model_DurationNoise <- 
lm(NPro_Dur_Ruis~H_Y,Regression_table)
get_regression_table(Model_DurationNoise)
broom::glance(Model_DurationNoise)
```
```{r}
Model_PectSemErr_Rep <- 
lm(PctSemNormRep~H_Y,allDataPatientStudyDS)
get_regression_table(Model_PectSemErr_Rep)
broom::glance(Model_PectSemErr_Rep)
```
```{r}
Model_Ntw_Perc_Sem_NErrors <- 
lm(Ntw_Perc_Sem_NErrors~H_Y,allDataPatientStudyDS)
get_regression_table(Model_Ntw_Perc_Sem_NErrors)
broom::glance(Model_Ntw_Perc_Sem_NErrors)
```



